### ISSUE TITLE
Cost

### ISSUE THREAD

**Issue by annimukherjee** [Prabrit/Sonar_System_LCD_#1]
Would be nice to include the costs of the components as well! Will help people to buy the components!

**Comment by Prabrit** [comment]
Appreciated and solved ; )

**Comment by Prabrit** [comment]
> Would be nice to include the costs of the components as well! Will help people to buy the components!
Appreciated and solved ; )

**Comment by Prabrit** [comment]
> Would be nice to include the costs of the components as well! Will help people to buy the components!

Appreciated and solved ; )
